
"use client";

import { KPICard } from "@/components/dashboard/kpi-card";
import { 
  Wallet, 
  Users, 
  KanbanSquare, 
  TrendingUp,
  AlertCircle,
  Clock,
  Rocket
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import Link from "next/link";

export default function DashboardHome() {
  return (
    <div className="flex flex-col gap-8 animate-in fade-in duration-500">
      <div>
        <h1 className="text-3xl font-bold font-headline mb-2">Welcome back, Founder</h1>
        <p className="text-muted-foreground">Here is the latest health overview of your startup.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <KPICard 
          title="Cash Runway" 
          value="14 Months" 
          icon={Clock} 
          description="Critical threshold: 6 months"
          trend={{ value: "2.4%", positive: true }}
        />
        <KPICard 
          title="Team Size" 
          value="12 People" 
          icon={Users} 
          description="2 hires pending"
          trend={{ value: "1", positive: true }}
        />
        <KPICard 
          title="Active Projects" 
          value="8" 
          icon={KanbanSquare} 
          description="3 nearing completion"
        />
        <KPICard 
          title="MRR" 
          value="$24,500" 
          icon={TrendingUp} 
          description="Next target: $30k"
          trend={{ value: "12%", positive: true }}
        />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <Card className="lg:col-span-2 shadow-md border-none">
          <CardHeader>
            <div className="flex items-center justify-between">
              <div>
                <CardTitle>Recent Milestones</CardTitle>
                <CardDescription>Major operational achievements this month.</CardDescription>
              </div>
              <Button variant="outline" size="sm" asChild>
                <Link href="/projects">View Projects</Link>
              </Button>
            </div>
          </CardHeader>
          <CardContent className="space-y-4">
            {[
              { title: "Beta Product Launch", date: "Oct 12, 2023", status: "Completed", icon: Rocket },
              { title: "Series A Deck Finalized", date: "Oct 28, 2023", status: "In Progress", icon: AlertCircle },
              { title: "Strategic Partnership with Acme Corp", date: "Nov 02, 2023", status: "Pending", icon: Users },
            ].map((milestone, i) => (
              <div key={i} className="flex items-center justify-between p-3 rounded-lg bg-secondary/30">
                <div className="flex items-center gap-3">
                  <div className="p-2 rounded-full bg-background shadow-sm">
                    <milestone.icon className="h-4 w-4 text-accent" />
                  </div>
                  <div>
                    <p className="text-sm font-semibold">{milestone.title}</p>
                    <p className="text-xs text-muted-foreground">{milestone.date}</p>
                  </div>
                </div>
                <span className={`text-[10px] font-bold uppercase px-2 py-1 rounded-full ${
                  milestone.status === 'Completed' ? 'bg-emerald-100 text-emerald-700' :
                  milestone.status === 'In Progress' ? 'bg-amber-100 text-amber-700' :
                  'bg-slate-200 text-slate-600'
                }`}>
                  {milestone.status}
                </span>
              </div>
            ))}
          </CardContent>
        </Card>

        <Card className="shadow-md border-none bg-primary text-primary-foreground">
          <CardHeader>
            <CardTitle className="text-xl">AI Growth Insights</CardTitle>
            <CardDescription className="text-primary-foreground/70">
              Immediate recommendations generated by your Intelligence Engine.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="p-4 rounded-xl bg-white/10 border border-white/20 backdrop-blur-sm">
              <p className="text-sm italic">
                "Based on current revenue growth, you should prioritize 'Expansion Hiring' in the next 45 days to maintain velocity."
              </p>
            </div>
            <Button variant="secondary" className="w-full font-bold group" asChild>
              <Link href="/ai-insights">
                Generate Full Analysis
                <TrendingUp className="ml-2 h-4 w-4 transition-transform group-hover:translate-x-1" />
              </Link>
            </Button>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
